version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "savage-kafka-order"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17247y1bzbwz9"
s3_prefix = "savage-kafka-order"
region = "us-west-2"
profile = "west-sandbox"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
